### ISSUE TITLE
Can't build in Mojave

### ISSUE THREAD

**Issue by gasparschott** [yb85/scantailor-advanced-osx#10]
Running 

`brew install ./scantailor.rb`
or
`brew install --HEAD ./scantailor.rb
`
fails with the following error:

```
==> make
Last 15 lines from /Users/MacBookPro/Library/Logs/Homebrew/scantailor/02.make:
          ^
/usr/local/opt/qt/include/QtCore/qpoint.h:103:18: note: forward declaration of 'QTransform'
    friend class QTransform;
                 ^
4 errors generated.
make[2]: *** [src/imageproc/CMakeFiles/imageproc.dir/BinaryThreshold.cpp.o] Error 1
4 errors generated.
make[2]: *** [src/imageproc/CMakeFiles/imageproc.dir/SeedFill.cpp.o] Error 1
[ 13%] Linking CXX executable ../../../math_tests
cd /tmp/scantailor-20200919-6958-9qx5wt/build/src/math/tests && /usr/local/Cellar/cmake/3.18.2/bin/cmake -E cmake_link_script CMakeFiles/math_tests.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/math_tests.dir/math_tests_autogen/mocs_compilation.cpp.o CMakeFiles/math_tests.dir/main.cpp.o CMakeFiles/math_tests.dir/TestHessians.cpp.o CMakeFiles/math_tests.dir/TestSqDistApproximant.cpp.o CMakeFiles/math_tests.dir/TestMatrixCalc.cpp.o -o ../../../math_tests  ../libmath.a /usr/local/lib/libboost_unit_test_framework-mt.dylib /usr/local/lib/libboost_prg_exec_monitor-mt.dylib ../../foundation/libfoundation.a /usr/local/opt/qt/lib/QtXml.framework/QtXml /usr/local/opt/qt/lib/QtGui.framework/QtGui /usr/local/opt/qt/lib/QtCore.framework/QtCore
make[1]: *** [src/imageproc/CMakeFiles/imageproc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 13%] Built target math_tests
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	26: from /usr/local/Homebrew/Library/Homebrew/build.rb:229:in `<main>'
	25: from /usr/local/Homebrew/Library/Homebrew/build.rb:140:in `install'
	24: from /usr/local/Homebrew/Library/Homebrew/utils.rb:496:in `with_env'
	23: from /usr/local/Homebrew/Library/Homebrew/build.rb:145:in `block in install'
	22: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1176:in `brew'
	21: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2150:in `stage'
	20: from /Users/MacBookPro/.gem/ruby/2.6.0/gems/forwardable-1.3.1/lib/forwardable.rb:235:in `stage'
	19: from /usr/local/Homebrew/Library/Homebrew/resource.rb:86:in `stage'
	18: from /usr/local/Homebrew/Library/Homebrew/resource.rb:111:in `unpack'
	17: from /usr/local/Homebrew/Library/Homebrew/resource.rb:201:in `mktemp'
	16: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
	15: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
	14: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
	13: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `block in unpack'
	12: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2170:in `block in stage'
	11: from /usr/local/Homebrew/Library/Homebrew/utils.rb:496:in `with_env'
	10: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2171:in `block (2 levels) in stage'
	 9: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1183:in `block in brew'
	 8: from /usr/local/Homebrew/Library/Homebrew/build.rb:177:in `block (2 levels) in install'
	 7: from /Volumes/SAMSUNG_256GB/PQI 64GB USB Drive 1/01 NEW APPS AND UPDATES/GRAPHICS APPS/DEWARP/scantailor-advanced-osx-master/scantailor.rb:30:in `install'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2084:in `mkdir'
	 5: from /Users/MacBookPro/.gem/ruby/2.6.0/gems/fileutils-1.4.1/lib/fileutils.rb:139:in `cd'
	 4: from /Users/MacBookPro/.gem/ruby/2.6.0/gems/fileutils-1.4.1/lib/fileutils.rb:139:in `chdir'
	 3: from /Volumes/SAMSUNG_256GB/PQI 64GB USB Drive 1/01 NEW APPS AND UPDATES/GRAPHICS APPS/DEWARP/scantailor-advanced-osx-master/scantailor.rb:32:in `block in install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1964:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1964:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2026:in `block in system': Failed executing: make (BuildError)
	5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:150:in `<main>'
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:162:in `rescue in <main>'
	3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:439:in `dump'
	2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:385:in `issues'
	1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:389:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:320:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)
```
Any ideas how to fix? I've tried to attach the log files, but it's not working, so here is a Dropbox link:
https://www.dropbox.com/sh/sc1fcrp5li6brp2/AAC6g6B4DU_hm3ZKE1r9htZga?dl=0

Thanks.

—Michael

**Comment by yb85** [comment]
latest build uses QT6 which may fix this issue
